name: validate

on:
  workflow_call:
  workflow_dispatch:
  push:




# The following jobs are equal for all IGs and can be moved to a common composite-action if 'uses'-support is added, see:
# https://github.com/actions/runner/blob/main/docs/adrs/1144-composite-actions.md
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get soft to validate
        uses: actions/checkout@main
        with:
          persist-credentials: false
          repository: M-Priour/validateCDA
          path: validateCDA

      # Get REPO
      - name: get REPO
        uses: actions/checkout@v3
        with:      
          path: testContenuCDA
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'      
      - name: Validate        
        run: |
          cd validateCDA
          mkdir D:/a/TestContenuCDA-3-0/TestContenuCDA-3-0/report/
          Get-ChildItem –Path "../testContenuCDA/ExemplesCDA/*.xml" –Recurse |
          Foreach-Object {
            java -cp ./librairie/* ./validate.java -i $_.FullName -o D:/a/TestContenuCDA-3-0/TestContenuCDA-3-0/report 
          }


        
      # Publishes the HTML page to a seperate branch in order to host it using GitHub-Pages.
      # This will overwrite the currently published HTML page.
      - name: 🚀 Deploy to GitHub-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          destination_dir: rapport/${{ steps.branch-name.outputs.current_branch }}
          commit_message: ' ${{ github.event.head_commit.message }}'
