name: validate

on:
  workflow_call:
  workflow_dispatch:




# The following jobs are equal for all IGs and can be moved to a common composite-action if 'uses'-support is added, see:
# https://github.com/actions/runner/blob/main/docs/adrs/1144-composite-actions.md
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get soft to validate
        uses: actions/checkout@main
        with:
          persist-credentials: false
          repository: M-Priour/validateCDA
          path: validateCDA

      # Get REPO
      - name: get REPO
        uses: actions/checkout@v3
        with:      
          path: testContenuCDA
      
      - name: Validate        
        run: |
          cd validateCDA
          java -cp ./librairie/* ./validate.java -i ../testContenuCDA/ExemplesCDA/ANEST-CR-ANEST_2022.01.xml -o ./report
      
        
      # Publishes the HTML page to a seperate branch in order to host it using GitHub-Pages.
      # This will overwrite the currently published HTML page.
      #- name: 🚀 Deploy to GitHub-Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./output
      #    destination_dir: ig/${{ steps.branch-name.outputs.current_branch }}
      #    exclude_assets: '**.zip,**.tgz,**.pack'
      #    commit_message: ' ${{ github.event.head_commit.message }}'
